const UserArticlesActionTypes = {
  SAVE_ARTICLE_START: "SAVE_ARTICLE_START",
  SAVE_ARTICLE_SUCCESS: "SAVE_ARTICLE_SUCCESS",
  SAVE_ARTICLE_FAILURE: "SAVE_ARTICLE_FAILURE",

  TOGGLE_PUBLISH_ARTICLE_START: "TOGGLE_PUBLISH_ARTICLE_START",
  TOGGLE_PUBLISH_ARTICLE_SUCCESS: "TOGGLE_PUBLISH_ARTICLE_SUCCESS",
  TOGGLE_PUBLISH_ARTICLE_FAILURE: "TOGGLE_PUBLISH_ARTICLE_FAILURE",

  DELETE_ARTICLE_START: "DELETE_ARTICLE_START",
  DELETE_ARTICLE_SUCCESS: "DELETE_ARTICLE_SUCCESS",
  DELETE_ARTICLE_FAILURE: "DELETE_ARTICLE_FAILURE",

  CREATE_ARTICLE_START: "CREATE_ARTICLE_START",
  CREATE_ARTICLE_SUCCESS: "CREATE_ARTICLE_SUCCESS",
  CREATE_ARTICLE_FAILURE: "CREATE_ARTICLE_FAILURE",

  FETCH_ARTICLES_START: "FETCH_ARTICLES_START",
  FETCH_ARTICLES_SUCCESS: "FETCH_ARTICLES_SUCCESS",
  FETCH_ARTICLES_FAILURE: "FETCH_ARTICLES_FAILURE",
}

export default UserArticlesActionTypes
