const UserActionTypes = {
  EMAIL_SIGN_UP_START: "EMAIL_SIGN_UP_START",
  EMAIL_SIGN_UP_SUCCESS: "EMAIL_SIGN_UP_SUCCESS",
  EMAIL_SIGN_UP_FAILURE: "EMAIL_SIGN_UP_FAILURE",

  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  EMAIL_SIGN_IN_SUCCESS: "EMAIL_SIGN_IN_SUCCESS",
  EMAIL_SIGN_IN_FAILURE: "EMAIL_SIGN_IN_FAILURE",

  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

  UPDATE_USER_PROFILE_START: "UPDATE_USER_PROFILE_START",
  UPDATE_USER_PROFILE_SUCCESS: "UPDATE_USER_PROFILE_SUCCESS",
  UPDATE_USER_PROFILE_FAILURE: "UPDATE_USER_PROFILE_FAILURE",

  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  USER_INITIALIZE_COMPLETED: "USER_INITIALIZE_COMPLETED",
}

export default UserActionTypes
