const EditArticleActionTypes = {
  COPY_ARTICLE: "COPY_ARTICLE",
  UPDATE_ARTICLE: "UPDATE_ARTICLE",
  UPDATE_ARTICLE_SECTIONS: "UPDATE_ARTICLE_SECTIONS",
  ADD_TO_ARTICLE_SECTION: "ADD_TO_ARTICLE_SECTION",
  DELETE_ARTICLE_SECTION: "DELETE_ARTICLE_SECTION",
  TOGGLE_SETTING_CARD: "TOGGLE_SETTING_CARD",
  ADD_TAG: "ADD_TAG",
  DELETE_TAG: "DELETE_TAG",

  ADD_SUBTITLE: "ADD_SUBTITLE",
  ADD_PARAGRAPH: "ADD_PARAGRAPH",
  ADD_HIGHLIGHT: "ADD_HIGHLIGHT",
  ADD_IMAGE: "ADD_IMAGE",

  UPLOAD_IMAGE_START: "UPLOAD_IMAGE_START",
  UPLOAD_IMAGE_SUCCESS: "UPLOAD_IMAGE_SUCCESS",
  UPLOAD_IMAGE_FAILURE: "UPLOAD_IMAGE_FAILURE",

  UPLOAD_MAIN_IMAGE_START: "UPLOAD_MAIN_IMAGE_START",
  UPLOAD_MAIN_IMAGE_SUCCESS: "UPLOAD_MAIN_IMAGE_SUCCESS",
  UPLOAD_MAIN_IMAGE_FAILURE: "UPLOAD_MAIN_IMAGE_FAILURE",
}

export default EditArticleActionTypes
